port: 3000

mongodb:
  uri: mongodb://localhost:27017
  databaseName: authenticate
  collections:
    users: users
    migrations: migrations_changelog
  migration:
    path: src/migrations

auth:
  salt: 10
  secret: this-is-my-secret
  accessTokenExpire: 15m
  refreshTokenExpire: 7d

logger:
  sensitives:
    - password
    - accessToken
    - refreshToken
    - req.headers.authorization
    - req.body.password
