port: 3000

mongodb:
  uri: mongodb://localhost:27017
  databaseName: authenticate
  collections:
    users: users
    migrations: migrations_changelog
  migration:
    path: src/migrations

auth:
  salt: 10